baseurl = "https://thelittledataset.com/"
languageCode = "en-us"
title = "The Little Dataset"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Data & Code"
    url = "/data_code/"
    weight = 3
[[menu.main]]
    name = "CV"
    url = "/about_files/alex-albright-cv.pdf"
    weight = 4    
[[menu.main]]
    name = "Support"
    url = "https://www.patreon.com/allbriteallday"
    weight = 5

[params]
    description = "The Little Dataset"
    footer = "&copy; Alex Albright 2019 | Built with [blogdown](https://github.com/rstudio/blogdown) & [Hugo](https://gohugo.io/)"
