baseurl = "https://thelittledataset.com/"
languageCode = "en-us"
title = "The Little Dataset"
theme = "hugo-xmin"
googleAnalytics = "UA-148934943-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "CV"
    url = "https://scholar.harvard.edu/files/apalbright/files/alex_albright_harvard_cv.pdf"
    weight = 3    
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 4       
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 5
[[menu.main]]
    name = "Public Goods"
    url = "/data_code/"
    weight = 6
#[[menu.main]]
#    name = "Job Market Info"
#    url = "/job-mkt-info/"
#    weight = 7   
#[[menu.main]]
#    name = "Support"
#    url = "https://www.patreon.com/allbriteallday"
#    weight = 7
   
[params]
    description = "The Little Dataset"
    footer = "&copy; [**Alex Albright**](https://thelittledataset.com/about/) 2014-2021 | Built with [blogdown](https://github.com/rstudio/blogdown) & [Hugo](https://gohugo.io/)"
