baseurl = "https://thelittledataset.com/"
languageCode = "en-us"
title = "The Little Dataset"
theme = "hugo-xmin"
googleAnalytics = "UA-148934943-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Alex Albright"
    url = "/alex-albright/"
    weight = 1
[[menu.main]]
    name = "CV"
    url = "https://thelittledataset.com/about_files/alex-albright-cv.pdf"
    weight = 2    
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3  
[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 4    
[[menu.main]]
    name = "Public Goods"
    url = "/data_code/"
    weight = 5
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 6    
[[menu.main]]
    name = "Misc."
    url = "/misc/"
    weight = 7
#[[menu.main]]
#    name = "Job Market Info"
#    url = "/job-mkt-info/"
#    weight = 7   
#[[menu.main]]
#    name = "Support"
#    url = "https://www.patreon.com/allbriteallday"
#    weight = 7
   
[params]
    description = "The Little Dataset"
    footer = "&copy; [Alex Albright](https://thelittledataset.com/alex-albright/) 2014-2022 | Built with [blogdown](https://github.com/rstudio/blogdown) & [Hugo](https://gohugo.io/)"
