baseurl = "https://thelittledataset.com/"
languageCode = "en-us"
title = "The Little Dataset"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1 
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2    
[[menu.main]]
    name = "Data & Code"
    url = "/my-resources/"
    weight = 3    
   
[params]
    description = "The Little Dataset"
    footer = "&copy; [Alex Albright](https://thelittledataset.com/about/) 2014-2025 | Built with [blogdown](https://github.com/rstudio/blogdown) + [Hugo](https://gohugo.io/) + trial and error"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true