baseurl = "https://thelittledataset.com/"
languageCode = "en-us"
title = "The Little Dataset"
theme = "hugo-xmin"
googleAnalytics = "UA-148934943-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Research"
    url = "https://scholar.harvard.edu/apalbright/research-1"
    weight = 3       
[[menu.main]]
    name = "CV"
    url = "/about_files/alex-albright-cv.pdf"
    weight = 4
[[menu.main]]
    name = "Resources"
    url = "/data_code/"
    weight = 5
#[[menu.main]]
 #   name = "Econ-y Resources"
  #  url = "/ec_resources/"
   # weight = 5    
#[[menu.main]]
#    name = "Support"
#    url = "https://www.patreon.com/allbriteallday"
#    weight = 6
#[[menu.main]]
#    name = "Teaching"
#    url = "/teaching/"
#    weight = 7    

[params]
    description = "The Little Dataset"
    footer = "&copy; Alex Albright 2021 | Built with [blogdown](https://github.com/rstudio/blogdown) & [Hugo](https://gohugo.io/)"
